### ISSUE TITLE
uncompress the assets and make releases to distribute

### ISSUE THREAD

**Issue by takouhai** [AltUniverseWash/HomestuckSlurReplacement#1]
currently, you're uploading a large amount of data with each commit, when github can do this for you. you need to decompress the assets and distribute this as [a release](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository) instead. you can [mark commits as releases](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and then continue working on the project without affecting the release in case something goes awry. 

i wouldn't keep uploading binary files, since you have to upload a lot, and users will have to download a lot to collaborate on your project.

**Comment by JonayaRiley** [comment]
Assets uncompressed and changed over to using release instead of re-uploading binaries every time.
